import { PDFDocument, PDFName, PDFNumber, PDFString } from "pdf-lib";

/** Test-only generated bytes. No real template, person, lease or legal content. */
export async function syntheticAcroform(
  names = ["Rent", "Tenant name"],
  marker = "SYNTHETIC TEST ONLY",
) {
  const pdf = await PDFDocument.create();
  pdf.setCreationDate(new Date("2026-01-01T00:00:00Z"));
  pdf.setModificationDate(new Date("2026-01-01T00:00:00Z"));
  const page = pdf.addPage([500, 500]);
  page.drawText(marker, { x: 30, y: 460, size: 10 });
  names.forEach((name, index) => {
    page.drawText(name, { x: 30, y: 410 - index * 55, size: 10 });
    pdf
      .getForm()
      .createTextField(name)
      .addToPage(page, { x: 30, y: 380 - index * 55, width: 360, height: 24 });
  });
  const signature = pdf.context.obj({
    FT: PDFName.of("Sig"),
    T: PDFString.of("Human signature"),
    Ff: PDFNumber.of(0),
  });
  if (names.length) pdf.getForm().acroForm.addField(pdf.context.register(signature));
  return pdf.save({ useObjectStreams: false });
}

/** Complete supported-field acceptance fixture; labels deliberately contain no legal content. */
export async function syntheticAcceptanceAcroform() {
  const pdf = await PDFDocument.create();
  pdf.setCreationDate(new Date("2026-01-01T00:00:00Z"));
  pdf.setModificationDate(new Date("2026-01-01T00:00:00Z"));
  const page = pdf.addPage([600, 800]),
    form = pdf.getForm();
  page.drawText("SYNTHETIC TEST ONLY - ALL SUPPORTED FIELDS", {
    x: 30,
    y: 765,
    size: 12,
  });
  for (const [index, name] of [
    "Amount",
    "Zero",
    "Date",
    "Party 1",
    "Party 2",
    "Animal 1",
    "Animal 2",
    "Preserved",
  ].entries()) {
    const y = 705 - index * 70;
    page.drawText(name, { x: 30, y: y + 30, size: 10 });
    form.createTextField(name).addToPage(page, { x: 30, y, width: 240, height: 24 });
  }
  for (const [index, name] of ["Checked", "Unchecked"].entries()) {
    const y = 705 - index * 70;
    page.drawText(name, { x: 330, y: y + 30, size: 10 });
    form.createCheckBox(name).addToPage(page, { x: 330, y, width: 20, height: 20 });
  }
  const radio = form.createRadioGroup("Radio");
  page.drawText("Radio: Option A / Option B", { x: 330, y: 595, size: 10 });
  radio.addOptionToPage("Option A", page, { x: 330, y: 565, width: 20, height: 20 });
  radio.addOptionToPage("Option B", page, { x: 390, y: 565, width: 20, height: 20 });
  const dropdown = form.createDropdown("Dropdown");
  dropdown.addOptions(["Option A", "Option B"]);
  page.drawText("Dropdown", { x: 330, y: 525, size: 10 });
  dropdown.addToPage(page, { x: 330, y: 495, width: 220, height: 24 });
  const list = form.createOptionList("List");
  list.addOptions(["Option A", "Option B"]);
  page.drawText("List", { x: 330, y: 455, size: 10 });
  list.addToPage(page, { x: 330, y: 405, width: 220, height: 44 });
  const signature = pdf.context.obj({
    FT: PDFName.of("Sig"),
    T: PDFString.of("Human signature"),
    Ff: PDFNumber.of(0),
  });
  form.acroForm.addField(pdf.context.register(signature));
  page.drawText("Human signature remains unsigned", { x: 330, y: 340, size: 10 });
  return pdf.save({ useObjectStreams: false });
}
