import { describe, expect, it } from "vitest";
import {
  buildCutoverReport,
  buildRollbackPlan,
  parseCutoverReportArgs,
  PRODUCTION_SMOKE_CHECKLIST,
  readRunbookSmokeChecklist,
  validatePriorRevision,
} from "../../scripts/build-cutover-report.mjs";
import { createDeployRevisionSuffix } from "../../scripts/deploy-demo-cloud-run.mjs";

const normalize = (text) => text.replace(/\s+/g, " ").trim();

describe("cutover report args", () => {
  it("parses manifest, env-file, project, location, prior revision, and json", () => {
    expect(
      parseCutoverReportArgs([
        "--manifest=temp/manifest.json",
        "--env-file=.env.production.local",
        "--project=pmikc-prod",
        "--location=us",
        "--prior-revision=pmi-kc-app-00041-prior",
        "--json",
      ]),
    ).toEqual({
      envFile: ".env.production.local",
      help: false,
      json: true,
      location: "us",
      manifest: "temp/manifest.json",
      priorRevision: "pmi-kc-app-00041-prior",
      project: "pmikc-prod",
    });
  });

  it("rejects unknown, duplicate, and empty arguments", () => {
    expect(() => parseCutoverReportArgs(["--manfest=temp/manifest.json"])).toThrow(
      "Unknown cutover report argument",
    );
    expect(() =>
      parseCutoverReportArgs(["--manifest=one.json", "--manifest=two.json"]),
    ).toThrow("Duplicate cutover report argument");
    expect(() => parseCutoverReportArgs(["--manifest="])).toThrow("requires a value");
    expect(() => parseCutoverReportArgs(["--service=pmi-kc-kb"])).toThrow(
      "Unknown cutover report argument",
    );
    expect(() => parseCutoverReportArgs(["--region=europe-west1"])).toThrow(
      "Unknown cutover report argument",
    );
  });
});

describe("smoke checklist doc sync", () => {
  it("matches the runbook §7 checklist bullets", () => {
    const documented = readRunbookSmokeChecklist();

    expect(documented.length).toBe(PRODUCTION_SMOKE_CHECKLIST.length);
    expect(PRODUCTION_SMOKE_CHECKLIST.map((item) => normalize(item.description))).toEqual(
      documented.map(normalize),
    );
  });

  it("gives every checklist item a unique id", () => {
    const ids = PRODUCTION_SMOKE_CHECKLIST.map((item) => item.id);

    expect(new Set(ids).size).toBe(ids.length);
  });
});

describe("rollback plan", () => {
  it("orders rollback steps from deploy back to rules", () => {
    const plan = buildRollbackPlan({
      project: "pmikc-prod",
      priorRevision: "pmi-kc-app-00041-prior",
      dataStoreIds: ["kb-lease-renewals-txt"],
      uploadedUris: ["gs://bucket/lease-renewals/sop.txt"],
      seededSpaceIds: ["lease-renewals"],
    });

    expect(plan.map((step) => step.step)).toEqual([1, 2, 3, 4, 5]);
    expect(plan[0].commands[0]).toContain("gcloud run services update-traffic");
    expect(plan[0].commands[0]).toContain("--to-revisions=pmi-kc-app-00041-prior=100");
    expect(plan.slice(1).every((step) => step.commands.length === 0)).toBe(true);
    expect(plan[1].note).toContain("kb-lease-renewals-txt");
    expect(plan[2].note).toContain("gs://bucket/lease-renewals/sop.txt");
    expect(plan[3].note).toContain("spaces/lease-renewals");
    expect(plan[4].note).toContain("immutable pre-deploy configuration reference");
    expect(JSON.stringify(plan)).not.toContain("confirm-delete");
    expect(JSON.stringify(plan)).not.toContain("gcloud storage rm");
    expect(JSON.stringify(plan)).not.toContain("firebase -- deploy");
    expect(JSON.stringify(plan)).not.toContain("gcloud run services delete");
  });

  it("uses placeholders when concrete identifiers are unknown", () => {
    const plan = buildRollbackPlan();

    expect(plan[0].commands).toEqual([]);
    expect(plan[0].note).toContain("Capture the currently serving");
    expect(plan.slice(1).every((step) => step.commands.length === 0)).toBe(true);
    expect(plan[1].note).toContain("<data-store-id>");
    expect(plan[2].note).toContain("gs://<client-source-bucket>");
  });

  // Regression guard. The rollback validator previously accepted ONLY Cloud Run's auto-generated
  // `<service>-00041-abc` form, while our own deploy wrapper creates `<service>-r<base36>-<12hex>`.
  // Every revision this repository deploys was therefore rejected and the rollback step emitted no
  // restore command at all. The revision name below is generated by the REAL deploy function, so
  // the two grammars cannot drift apart again without failing this test.
  it("accepts a prior revision generated by this repository's own deploy wrapper", () => {
    const service = "pmi-kc-app";
    const suffix = createDeployRevisionSuffix({
      nowMs: Date.parse("2026-07-28T12:00:00.000Z"),
      entropy: "92c1b759735e",
    });
    const revision = `${service}-${suffix}`;

    expect(validatePriorRevision(service, revision)).toBe(revision);

    const plan = buildRollbackPlan({ project: "pmikc-prod", priorRevision: revision });
    expect(plan[0].commands).toHaveLength(1);
    expect(plan[0].commands[0]).toContain(`--to-revisions=${revision}=100`);
  });

  it("accepts a recorded serving revision in the deploy-wrapper form", () => {
    // Shape taken from the environment handoff registry's recorded serving revisions.
    const revision = "pmi-kc-app-rmrxpsn5q-92c1b759735e";
    expect(validatePriorRevision("pmi-kc-app", revision)).toBe(revision);
  });

  it("still refuses a revision that is not a real revision name for this service", () => {
    for (const candidate of [
      "",
      "   ",
      "pmi-kc-app",
      "pmi-kc-app-latest",
      "other-service-00041-abc",
      "other-service-rmrxpsn5q-92c1b759735e",
      // Right shape, wrong entropy width.
      "pmi-kc-app-rmrxpsn5q-92c1b759735",
      // Injection attempt riding along with a plausible revision.
      "pmi-kc-app-00041-abc=100 --to-revisions=attacker=100",
    ]) {
      expect(
        validatePriorRevision("pmi-kc-app", candidate),
        `${candidate} must be refused`,
      ).toBeUndefined();
      expect(buildRollbackPlan({ priorRevision: candidate })[0].commands).toEqual([]);
    }
  });
});

// Point every composition case at an empty env fixture so readProductionPreflightEnv does not
// read the host's on-disk `.env.local`. Otherwise a developer machine that carries a real
// GCP_PROJECT_ID (e.g. pmi-kc-kb-prod) suppresses the expected "no target project id" gcp:
// blocker and the first case fails only locally — the same env-coupling class as the
// migration-readiness smoke test.
const HERMETIC_ENV_FILE = "--env-file=tests/fixtures/empty-env.fixture";

describe("cutover report composition", () => {
  it("aggregates blockers across sections with prefixes", () => {
    const report = buildCutoverReport({
      argv: [HERMETIC_ENV_FILE],
      env: { ASK_DEMO_MODE: "true" },
      awayModeActive: true,
    });

    expect(report.readiness.ok).toBe(false);
    expect(report.readiness.blockers.some((blocker) => blocker.startsWith("gcp:"))).toBe(
      true,
    );
    expect(report.readiness.blockers.some((blocker) => blocker.startsWith("env:"))).toBe(
      true,
    );
    expect(
      report.readiness.blockers.some((blocker) => blocker.startsWith("corpus:")),
    ).toBe(true);
    expect(report.smoke_checklist).toEqual(PRODUCTION_SMOKE_CHECKLIST);
    expect(report.rollback.length).toBe(5);
    expect(report.rollback_ready).toBe(false);
    expect(
      report.readiness.blockers.some((blocker) => blocker.startsWith("rollback:")),
    ).toBe(true);
    expect(JSON.stringify(report.rollback)).not.toContain("services delete");
    expect(report.deploy.command_preview).toBe("");
    expect(report.mode).toBe("dry-run");
  });

  it("evaluates the production manifest template and reports corpus blockers", () => {
    const report = buildCutoverReport({
      argv: [
        HERMETIC_ENV_FILE,
        "--manifest=docs/source-corpus/client-production-source-manifest.template.json",
        "--project=pmikc-kb-production",
        "--location=us",
      ],
      env: { ASK_DEMO_MODE: "true" },
      awayModeActive: true,
    });

    expect(report.corpus.evaluated).toBe(true);
    expect(report.corpus.readiness.ok).toBe(false);
    expect(
      report.readiness.blockers.some((blocker) => blocker.startsWith("corpus:")),
    ).toBe(true);
    expect(report.corpus.upload_commands).toEqual([]);
    expect(report.rollback[1].commands).toEqual([]);
    expect(report.rollback[1].note).toContain("Candidate data stores");
  });

  it("treats a missing manifest path as a blocker, not a crash", () => {
    const report = buildCutoverReport({
      argv: [
        HERMETIC_ENV_FILE,
        "--manifest=temp/does-not-exist.json",
        "--project=pmikc-prod",
      ],
      env: { ASK_DEMO_MODE: "true" },
      awayModeActive: true,
    });

    expect(report.corpus.evaluated).toBe(false);
    expect(
      report.readiness.blockers.some((blocker) =>
        blocker.includes("manifest could not be evaluated"),
      ),
    ).toBe(true);
  });
});
